sudo: true
dist: trusty
language: python
python:
- '3.5'
env:
- TOX_ENV=e-dictionary.apc
- TOX_ENV=moedict-twblg
- TOX_ENV=flake8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
    - python3-dev
    - libc6-dev-i386
    - linux-libc-dev
    - gcc-multilib
    - git
    - subversion
    - automake
    - libtool
    - zlib1g-dev
    - libbz2-dev
    - liblzma-dev
    - libboost-all-dev
    - libgoogle-perftools-dev
    - libxmlrpc-c++.*-dev
    - cmake
    - csh
    - libyaml-dev
    - libxslt1-dev
    - libav-tools
    - libmp3lame0
install:
- sudo dpkg --add-architecture i386
- sudo apt-get update
- sudo apt-get install libx11-dev libx11-dev:i386
- pip install tox
- pip install python-coveralls
branches:
  only:
  - master
  - "/\\d+\\.\\d+\\.\\d+/"
script:
- tox -e $TOX_ENV
after_success:
- coverage report
- coveralls
deploy:
  provider: pypi
  user: sih4sing5hong5
  password:
    secure: XmUU5CmA8ovy4B2EcEUrKYTE54Nr83hlWfou9vDkywWgIynS/ia0wFQLlA6pER6/4BA4TsW9BuTfgW4Cepni/o5sVyl6LZvxb9Mr68fRONrkKrjExpgm/HWz3EU7zLIFCeCYAjyZQdyZazpkn+P0XLidExHov+5L8RyN1US3IrxAgmxzrkpIMCB2v2w9bG6BqA6CGE4uN8vxARIvtDYRRea3drIRRjOaVcBXKG0PnyAGbZy2nNJv3Qmo+Vv/JXZ5O0DMPFX44sXZ7t5UgFEFytVawgCEo0ae523i8t90tEPK9iYruJ3BS+1cgSSt19RRqXRcTO/SeBcGAI79KjVPwMGeVvks1axxnKjR5U5EYLV66DnhdURxlFUvOr4UYXJOJH99iv90MpnHvx9KwPKicbgXlFqAks5jITSMFwzKg6jpRjx2rGQ2kIOP1qSJuEyMNRhL7FvmdoUAB/3KczZ6Qp9kE+DDtoIEw/+B2lpoifgpx2sfO3uMclZOvpR8k5+KJLPEr9K5EkwT870E0hixWHe5n5IDeNznsOlWd3QpI7OPSuJwGugiMLPVWI5+kMr0n4hKPxjhgsRcR3T5XrXpty9Vcpir7HdQhBh7kxyEtvlVnWH/lhkSkP6Vo8Z+2IUUM0571Rnw2hzoHJKNn28sRc4i+941m0F0a8KV19AZEX8=
  on:
    tags: true
    repo: sih4sing5hong5/hue7jip8
