代碼對應 = {
    'Pangcah': 'ami', 'Amis': 'ami', '阿美語': 'ami',
    'Atayal': 'tay', '泰雅語': 'tay',
    'Paiwan': 'pwn', '排灣語': 'pwn',
    'Bunun': 'bnn', '布農語': 'bnn',
    'Puyuma': 'pyu', '卑南語': 'pyu',
    'Drekay': 'dru', '魯凱語': 'dru',
    'Tsou': 'tsu', '鄒語': 'tsu',
    'SaySiyat': 'xsy', '賽夏語': 'xsy',
    'Tao': 'tao', '達悟語': 'tao', 'Yami': 'tao', '雅美語': 'tao',
    'Thau': 'ssf', '邵語': 'ssf',
    'Kavalan': 'ckv', '噶瑪蘭語': 'ckv',
    'Truku': 'trv', '太魯閣語': 'trv',
    'Sakizaya': 'ais', '撒奇萊雅語': 'ais',
    'Seediq': 'sdq', '賽德克語': 'sdq',
    'Hla\'alua': 'sxr', '拉阿魯哇語': 'sxr',
    'Kanakanavu': 'xnb', '卡那卡那富語': 'xnb',
}
